// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:birdo/model/entities/day.dart';
import 'package:birdo/model/entities/pet.dart';
import 'package:birdo/model/entities/pet_energy.dart';
import 'package:birdo/model/entities/rainbow_stones.dart';
import 'package:birdo/model/entities/task.dart';
import 'package:birdo/model/entities/user.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DayAdapter());
    registerAdapter(GenderAdapter());
    registerAdapter(PetAdapter());
    registerAdapter(PetEnergyAdapter());
    registerAdapter(PetGrowthStageAdapter());
    registerAdapter(RainbowStonesAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(TaskCategoryAdapter());
    registerAdapter(UserAdapter());
  }
}
